spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hotel}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
security:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: PT8H
  bootstrap-admin-username: ${BOOTSTRAP_ADMIN_USERNAME}
  bootstrap-admin-password: ${BOOTSTRAP_ADMIN_PASSWORD}
