package com.example.hotel.dto.common.request;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Contains the mutable profile fields supplied when creating a Staff member. The Staff Code is
 * never accepted here — it is generated by the backend.
 *
 * @param firstName required first name
 * @param lastName required last name
 * @param phone optional phone number
 * @param email optional email address, validated when supplied
 * @param position optional free-text position (e.g. Receptionist, Housekeeping)
 * @param startDate required employment start date
 * @param notes optional notes
 */
public record StaffCreateRequest(
        @NotBlank(message = "{validation.staff.firstName.required}") @Size(max = 100, message = "{validation.size.max}") String firstName,
        @NotBlank(message = "{validation.staff.lastName.required}") @Size(max = 100, message = "{validation.size.max}") String lastName,
        @Size(max = 100, message = "{validation.size.max}") String phone,
        @Email(message = "{validation.staff.email.invalid}") @Size(max = 255, message = "{validation.size.max}") String email,
        @Size(max = 100, message = "{validation.size.max}") String position,
        @NotNull(message = "{validation.staff.startDate.required}") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
        @Size(max = 1000, message = "{validation.size.max}") String notes) {}
